// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package models

import (
	"time"

	"github.com/google/uuid"
)

type FirebaseToken struct {
	ID        int64
	Token     string
	Cid       uuid.UUID
	Active    bool
	Expiresat time.Time
}
